_BASE_: "./base/retinanet_R_50_FPN_3x.yaml"
INPUT:
  MAX_SIZE_TRAIN: (1280)
DATASETS:
  TRAIN: ("letters_dataset", )
MODEL:
  RETINANET:
    SCORE_THRESH_TEST: 0.000
    NMS_THRESH_TEST: 0.2
OUTPUT_DIR: "model/letters/retina-r50/"